name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
      env:
        CI: true
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.ref == 'master'
    - name: Release with Node.js 8.x
      if: github.ref == 'master'
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: release with semantic-release
      if: github.ref == 'master'
      run: npm run semantic-release
      env:
        CI: true
